# Generated by Django 3.1 on 2021-01-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210112_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='i/static/m/static/g/static/s/static//'),
        ),
    ]
